### ISSUE TITLE
Link to examples from robotframework-faker readme

### ISSUE THREAD

**Issue by guykisel** [laurentbristiel/robotframework-faker-example#1]
@laurentbristiel do you mind if I link to this repo from https://github.com/guykisel/robotframework-faker/blob/master/README.rst ?

**Comment by guykisel** [comment]
Alternatively, I can add you to robotframework-faker as a collaborator if you'd like to put your examples directly in that repo :smile:

**Comment by laurentbristiel** [comment]
You can add a link of course. No Problem. This is just me playing around though. Nothing terrific. Don't have much bandwidth but trying to contribute as I can.

**Comment by guykisel** [comment]
Cool, thanks. I think this is already pretty nice as-is.
